### ISSUE TITLE
Tests fail for a new package

### ISSUE THREAD

**Issue by niess** [grand-mother/pkg#8]
niess@clrtoport03:~/Soft/grand/handson/upgrade/mypackage$ python3 -m tests
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/niess/Soft/grand/handson/upgrade/mypackage/tests/__main__.py", line 32, in <module>
    r = not runner.run(suite()).wasSuccessful()
  File "/usr/local/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
TypeError: suite() takes 0 positional arguments but 1 was given

**Comment by niess** [comment]
Patched with ece0029ab96ef6afaed0abf928846ed95e74caf5. Old packages might need a `grand-pkg-update` though.
